# Generated by Django 4.2 on 2023-04-15 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 15, 11, 59, 7, 83354)),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 15, 11, 59, 7, 83850)),
        ),
    ]
