# Generated by Django 4.2 on 2023-04-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0004_article_datecreation_userresponse_datecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
